version: "3.8"

networks:
  backend:

volumes:
  pgdata:


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: netology_import_phones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  web:
     build: .
     command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata data.json && gunicorn main.wsgi:application --bind 0.0.0.0:7000"
     ports:
        - "7000:7000"
     networks:
       - backend
     depends_on:
       - db
