version: "3.9"

networks:
  backend:

volumes:
  pgdata:


services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    env_file:
#      - ./.env.db
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_import_phones"]
#      interval: 1m30s
#      timeout: 30s
#      retries: 5
#      start_interval: 30s
#    restart: unless-stopped
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"
  web:
     build: .
     command: sh -c "python manage.py migrate && gunicorn main.wsgi:application --bind 0.0.0.0:7000"
     ports:
        - "7000:7000"
     networks:
       - backend
     depends_on:
       - db
#     environment:
#       - DEBUG=1
#       - DJANGO_SECRET_KEY=your_secret_key
#       - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
#       - DATABASE_URL=postgres://postgres:rS8-t3j-3V7-gb8@127.0.0.1:5432/netology_import_phones
#     env_file:
#       - ./.env.db

#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "80:80"
#    depends_on:
#      - backend